{% set name = "fractal-task-tools" %}
{% set version = "0.1.1" %}
{% set python_min = "3.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fractal_task_tools-{{ version }}.tar.gz
  sha256: 4191f586e62442afd9bbe28073082be8c2dceb69ccb7ad4b47b1747c93650d87

build:
  entry_points:
    - fractal-manifest = fractal_task_tools._cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }},<3.13.0
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }},<3.13.0
    - pydantic >=2.0.0,<=2.11.2
    - docstring_parser >=0.15,<=0.16
    - packaging

test:
  imports:
    - fractal_task_tools
  commands:
    - pip check
    - fractal-manifest --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Shared tools for Fractal tasks
  home: https://github.com/fractal-analytics-platform/fractal-task-tools
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mfranzon
    - jluethi
    - tcompa
